version: '2.3'

services:
  hds:
    build:
      context: .
      args:
        version: <VERSION>
        buildnum: <BUILDNUM>
    image: linksmart/historical-datastore
  tester:
    build:
      context: .
      target: builder
    depends_on:
      - hds
    environment:
      - HDS_ENDPOINT=http://hds:8085
    command: go test -mod=vendor -v ./...

# RUN
# docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
